---
swagger: "2.0"
info:
  description: "The YAML file of the experience API of facial recognition app"
  version: "1.0"
  title: "Experience API"
tags:
- name: "image"
  description: "the photo that will be send to Watson"
- name: "class"
  description: "classification of the image"
- name: "score"
  description: "the score watson correctly classified the image"
- name: "count"
  description: "the number of times Watson recognized the same image type"
schemes:
- "https"
- "http"
paths:
  /image:
    post:
      tags:
      - "image"
      summary: "posts image to Watson"
      operationId: "postImage"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "file"
        in: "formData"
        description: "image that needs to be posted"
        required: true
        type: "file"
        format: "PNG, JPEG, JPG"
      responses:
        200:
          description: "succesfull operation"
        405:
          description: "Invalid input"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "Image"
  /class:
    post:
      tags:
      - "class"
      summary: "posts class of image"
      operationId: "postClass"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "body of the title"
        required: true
        schema:
          $ref: "#/definitions/body"
      responses:
        200:
          description: "succesfull operation"
          schema:
            $ref: "#/definitions/response"
      x-swagger-router-controller: "Class"
  /score:
    post:
      tags:
      - "score"
      summary: "the score the watson correctly classified the image"
      operationId: "postScore"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "chanceBody"
        description: "gives the chance"
        required: true
        schema:
          $ref: "#/definitions/number"
      responses:
        405:
          description: "Invalid input"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "Score"
  /count:
    post:
      tags:
      - "count"
      summary: "posts count of the object"
      operationId: "postCount"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "countBody"
        description: "gives the count"
        required: true
        schema:
          $ref: "#/definitions/number"
      responses:
        405:
          description: "Invalid input"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "Count"
definitions:
  response:
    type: "object"
    properties:
      title:
        type: "string"
      chance:
        type: "integer"
        format: "int64"
      count:
        type: "integer"
        format: "int64"
    example:
      chance: 0
      count: 6
      title: "title"
  body:
    type: "string"
  number:
    type: "integer"
