swagger: "2.0"
info:
  description: "the interface between the Master API and Watson"
  version: "1.0.0"
  title: "WatsonSystemAPi"
host: "cloud.something.ai"
basePath: "/v1"
schemes:
- "http"
paths:
  /inputpicture/{categorie}:
    post:
      tags:
      - "input"
      summary: "receives the picture to and send it to Watson"
      description: ""
      operationId: "inputpicture"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "categorie"
        in: "path"
        description: "The catagorie of where to find the answer bv fruit"
        required: true
        type: "string"
      - name: "file"
        in: "formData"
        description: "file to upload"
        required: false
        type: "file"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Response"
        405:
          description: "Invalid input"
definitions:
  Response:
    type: "object"
    properties:
      categorie:
        type: "string"
        example: "banana"
      score:
        type: "number"
        format: "float"