---
swagger: "2.0"
info:
  description: "the interface between the Master API and Watson"
  version: "1.0.0"
  title: "WatsonSystemAPi"
host: "cloud.something.ai"
tags:
- name: "image"
  description: "the photo that will be send to Watson"
- name: "class"
  description: "classification of the image"
- name: "score"
  description: "the score watson correctly classified the image"
- name: "count"
  description: "the number of times Watson recognized the same image type"
schemes:
- "http"
paths:
  /image:
    post:
      tags:
      - "image"
      summary: "receives the image to and send it to Watson"
      description: ""
      operationId: "image"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "image"
        in: "formData"
        description: "The class of where to find the answer bv banana"
        required: true
        type: "file"
        format: "PNG, JPEG, JPG"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Response"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Image"
definitions:
  Response:
    type: "object"
    properties:
      categorie:
        type: "string"
        example: "banana"
      score:
        type: "number"
        format: "float"
    example:
      score: 0.8008282
      categorie: "banana"
