swagger: "2.0"
info:
  description: "The YAML file of the sysAPI for MongoDB."
  version: "1.0.1"
  title: "MongoDB Image Recognition"
tags:
- name: "image"
  description: "the photo that will be send to Watson"
- name: "class"
  description: "classification of the image"
- name: "score"
  description: "the score watson correctly classified the image"
- name: "count"
  description: "the number of times Watson recognized the same image type"
schemes:
- "https"
- "http"
paths:
  /foto:
    post:
      tags:
      - "image"
      summary: "Add a new image to the database"
      operationId: "addImage"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "image that needs to be added to the database"
        required: true
        schema:
          $ref: "#/definitions/image"
      responses:
        405:
          description: "Invalid input"
        200:
          description: "successful operation"
    get:
      tags:
      - "count"
      summary: "get count of recognised office furniture in the database"
      description: "returns a number of class entries"
      operationId:  "getFoto"
      parameters: []
      responses:
        405:
          description: "Invalid input"
        200:
          description: "succesful operation"
          schema:
            type: "object"
            properties:
              class_entries:
                type: "integer"
                format: "int32"
definitions:
  image:
    type: "object"
    required:
    - "class"
    - "score"
    properties:
      requestId:
        type: "integer"
        format: "int64"
      class:
        type: "string"
        example: "clock"
      score:
        type: "number"
        format: "float"
        exclusiveMaximum: true
        maximum: 1
        exclusiveMinimum: true
        minimum: 0
      requestdatum: 
        type: "string"
        format: "date-time"